import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>The Liberty House</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="topheader">
        <h1 id="pageheader">The Liberty House</h1>
        <h1 id="pageheadershadow">The Liberty House</h1>
        <h2 id="pageheaderinfo">Est. 2023 - Clinton, La</h2>
        <h2 id="pageheaderinfoshadow">Est. 2023 - Clinton, La</h2>
        <a id="call" href="tel:+1234567890">
          Place your order at: (225) 683-9342
        </a>
      </div>
      <div id="menu">
        <li id="WWB">Where We Begin: </li>
        <br></br>
        <li id="drinks"> Drinks</li>{" "}
        <ul id="specialbrew">Liberty House Special Brew:</ul>
        <ul id="coffeeinfo">
          12 oz.: (Hot) ...2.95$, (Iced) ...3.35${" "}
          <ul>*Add StroopWafel ...1.15$</ul>
          <ul>**Iced Coffee can be served with condensed milk. Yum!</ul>
        </ul>
        <ul id="tea">Premium, Organic Iced Tea:</ul>
        <ul id="teainfo">
          (Black/Hibiscus/Mixed)<ul>16 oz ...2.29$</ul>
        </ul>
        <ul id="orangejuice">
          Orange Juice: <ul>...1.89$</ul>
        </ul>
        <ul id="hotchocolate">Hot Chocolate: (Oct. - Mar.) </ul>
        <ul id="hotchocinfo">
          <ul>(Regular or Peppermint)</ul>
          <ul>12 oz. ...2.49$</ul>
          <ul>Add Cinnamon Chips (Optional)</ul>
          <ul>Add Mini-Marshmellows</ul>
        </ul>
        <ul id="bottledwater">
          Bottled Water: <ul> ...0.99$</ul>
        </ul>
      </div>
    </>
  );
}
