import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [aboutButtonClicked, setAboutButtonClicked] = useState(false);
  const [menuButtonClicked, setMenuButtonClicked] = useState(false);

  const handleAboutButtonClick = () => {
    setAboutButtonClicked(true);
    setMenuButtonClicked(false);
  };

  const handleMenuButtonClick = () => {
    setMenuButtonClicked(true);
    setAboutButtonClicked(false);
  };

  return (
    <>
      <Head>
        <title>Liberty House Specialties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  <div class="image-container1">
    <img id="house" src="/images/house11.png" alt="house"></img>
    <div class="menu-top">
    <div id="title">Liberty House Specialties</div>
  <div id="location">11652 Liberty Street, Clinton LA</div>
  <div className="topbuttons">
  <button  id="about" onClick={handleAboutButtonClick}>
    About Us
  </button>
  <button id="menu" onClick={handleMenuButtonClick}> 
    Our Menu
  </button>
    <button  id="call">
      <a href="tel:+2256839342" id="callb">
      Call in your order</a>
    </button>
  
  </div>

      
  </div></div>
 

  <div
  id="images"
  style={{
    opacity: aboutButtonClicked && !menuButtonClicked ? 0 : 1,
    visibility: aboutButtonClicked && !menuButtonClicked ? 'hidden' : 'visible',
    transition: 'opacity 0.5s ease-in-out, visibility 0.5s ease-in-out',
  }}
>
  <div class="image-container">
    <img id="coffeeimage" src="/images/coffee.png" alt="Coffee"></img>
    <div class="menu-content">
    <div id="menucoffeeheader">Liberty House Special Brew:</div><div id="menucoffee">
        <li className="coffeelist coffeelisttwelve"><div id="hot">Hot</div><ul className="coffeelist subtwelvehot">(12oz.)<br></br>  ...2.95</ul>
        <ul className="subtwelvecold">(16oz) <br></br> ...3.95</ul></li>
        <li className="coffeelistsix"><div id="iced">Iced**</div><ul className="subsixhot">(12oz.)<br></br> ...3.35</ul>
        <ul className="subsixcold">(16oz.) <br></br> ...4.25</ul>
        </li>
        <div id="milknote"><div id="stroop">Add Stroopwafel  ...1.15</div><br></br><div id="icednote">**Iced coffee can be served with condensed milk. Yum!</div></div>
       </div>
    </div>
  </div>

  <div class="image-container">
    <img id="teaimage" src="/images/tea.png" alt="Tea"></img>
    <div class="menu-content">
    <div className="tealist">Premium,<br></br> Organic Iced Tea</div> 
       <div className="menutea">
          
          <li id="teasix"><div id="teatype">Black/Hibiscus/Mixed </div>
          <div id="teaprice">...2.29 </div></li>

    </div>
  </div>
  </div>

    <div class="image-container">
    <img id="orangeimage" src="/images/orange.png" alt="Orange Juice"></img>
    <div class="menu-content"><div id="orangeheader">Orange Juice</div>
          <div id="menuorange"> 
          <li id="orangeprice">
            <div id="wholeorange"><div id="glass">By the bottle</div>
            <div id="op">...1.89</div></div></li>
          </div> 
    </div>
    </div>
    


<div class="image-container">
    <img id="hotchocimage" src="/images/hotchoc.png" alt="Hot Chocolate"></img>
    <div class="menu-content">
    <div id="hotchocheader">Hot Chocolate</div> <div id="limited">(Oct. - Mar)</div> 
        <div id="menuhotchoc"> 
        
        <div id="regormint">Regular or Mint</div> <li id="hotchocprice"> 
        <div id="addins">Add-ins:<br></br>Cinnamon Chips or Mini-Marshmellows</div> 
        <div id="wholehotchoc"><div id="glasshotchoc">12oz.</div>
        <div id="hcp">...2.49</div></div></li>
        </div>
    </div>
    </div>

    <div class="image-container">
    <img id="croissantimage" src="/images/croissant.png" alt="Croissant"></img>
    <div class="menu-content">
      
    <div id="croissantheader">Croissants</div>
        <div id="menucroissant">
        <div id="croissantflavors">
        <li id="buttered">
        <div id="croissantflavor">Buttered</div><div id="cp1">...2.95</div></li>  
        <li id="ham">
        <div id="croissantflavor">Ham and Swiss</div><div id="cp2">...5.75</div></li>
        <li id="spinach">
        <div id="croissantflavor">Spinach and Feta</div><div id="cp5">...5.75</div></li>
        <li id="almond">
        <div id="croissantflavor">Almond</div><div id="cp3">...3.95</div></li>
        <li id="chocolate">
        <div id="croissantflavor">Chocolate</div><div id="cp4">...3.25</div></li>
       </div>
       </div> 
    </div>
    </div>

    <div class="image-container">
    <img id="blueberryimage" src="/images/blueberry.png" alt="Scone"></img>
    <div class="menu-content">
    <div id="scones">Scones</div>
      <div id="menuscone">
      <li id="sconeprice"><div id="blueberry">Blueberry</div><div id="bp">...3.75</div></li>
      </div>
    </div>
    </div>  

    <div class="image-container">
      <img id="brownimage" src="/images/brown.png" alt="Brown"></img> 
      <div class="menu-content">
      <div id="brownsugarcakeheader">Brown Sugar Walnut<br></br>Coffee Cake</div>
      <div id="menubrownsugarcake"> <li id="cakeprice"><div id="slice">Per Slice</div><div id="sliceprice">...3.25</div></li> </div>
      
      </div>
      </div>

      <div class="image-container">
        <img id="cheesedanishimage" src="/images/cheesedanish.png" alt="Cheese Danish"></img>
        <div class="menu-content">
      <div id="cheesedanishheader">Cheese Danish</div>
      <div id="menucheesedanish"> <li id="cheesedanishprice"><div id="slicecheese">Per Pastry</div><div id="slicepricecheese">...3.65</div></li> </div>
  
        </div>
        </div>

        <div class="image-container">
          <img  id="raspberrydanishimage" src="/images/raspberrydanish.png" alt="Raspberry Danish"></img>
          <div class="menu-content">
            
      <div id="raspberrydanishheader">Raspberry Danish</div>
      <div id="menuraspberrydanish"> <li id="raspberrydanishprice"><div id="sliceraspberry">Per Pastry</div><div id="slicepriceraspberry">...3.75</div></li> </div>

          </div>
          </div>

          <div class="image-container">
            <img id="biscuitimage" src="/images/biscuit.jpg" alt="Biscuit"></img>
            <div class="menu-content">
              
      <div id="biscuitheader">Biscuits</div>
      <div id="menubiscuit"> <li id="biscuitprice"><div id="biscuitprice1">Large Buttermilk Biscuit w/ Butter</div><div id="biscuitprice2">...2.49</div></li> <li id="fixings">Add Preserves (Strawberry or Blackberry) ...0.59<br></br>Add Deer Sausage Patty ...1.99<br></br>Add Cream Cheese ...0.99<br></br>Add Egg Bite* ...3.59</li></div>

            </div>
            </div>

            <div class="image-container">
              <img id="bagelimage" src="/images/bagel.png" alt="Bagel"></img>
              <div class="menu-content">
      <div id="bagelheader">Bagels</div>
      <div id="menubagel"> <li id="bagelprice"><div id="bagelprice1">Plain Bagel w/ Butter<br></br></div><div id="bagelprice2">...2.69</div></li> <li id="fixings2">(Substitute Cinnamon Butter  ...0.30) <br></br>Add Preserves (Strawberry or Blackberry) ...0.59<br></br>Add Deer Sausage Patty ...1.99<br></br>Add Cream Cheese ...0.99<br></br>Add Egg Bite* ...3.59</li></div>

              </div>
              </div>

              <div class="image-container">
                <img id="eggimage" src="/images/egg.png" alt="Egg"></img>
                <div class="menu-content">
      <div id="eggheader">Egg Bites</div>
      <div id="menuegg"> <li id="eggprice"><div id="eggprice1">Egg Bite* (2 per order)</div><div id="eggprice2">...5.99</div></li> <li id="eggfixings">*Options: 1. Ham and Cheddar Chili Pepper,
<br></br>2. Prosciutto gruyere, 3. Spinach Feta</li></div>

          </div>
          </div>
        <div class="image-container">
          <img id="oatmealimage" src="/images/oatmeal.jpg" alt="Oatmeal"></img>
          <div class="menu-content">
          <div id="oatmealheader">Oatmeal</div> <div id="oatmealflavors">Brown Sugar or Maple</div>
<div id="menuoatmeal"> <li id="oatmealprice"><div id="oatmealprice1">Per Bowl</div><div id="oatmealprice2">...3.79</div>
</li> <div id="pecans">Add Chopped Pecans</div><div id="pecanprice">...0.65</div></div>
          </div>
          </div>
</div>

<div
  id="aboutus"
  style={{
    opacity: (!aboutButtonClicked && !menuButtonClicked) || (!aboutButtonClicked && menuButtonClicked) ? 0 : 1,
    visibility: (!aboutButtonClicked && !menuButtonClicked) || (!aboutButtonClicked && menuButtonClicked) ? 'hidden' : 'visible',
    transition: 'opacity 0.5s ease-in-out, visibility 0.5s ease-in-out',
  }}
><h1 id="aboutblurb"><div id="textblurb">
         Hours: <br></br>Mon-Fri - 6AM to 12PM<br>
          </br>Sat - 7AM to 12PM<br></br><br></br>11652 Liberty Street<br></br>
          Clinton, LA 70722
          <br></br>
          <a>(225) 683-9342</a>
          <br></br>
         <br></br>About us: <br></br>Liberty House, Circa 1868,
          housed the first general store in
          the Feliciana parishes. Standing
          tall, Liberty House still proudly
          serves the Feliciana parishes with
          the same dedication to excellent
          products, service, and long-term
          relationships with the members
          of our community. <br></br><br></br>Thank you for allowing us to be
          a part of your day!
          </div></h1>
          </div>
    </>
  );
}
