import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [aboutButtonClicked, setAboutButtonClicked] = useState(false);
  const [menuButtonClicked, setMenuButtonClicked] = useState(false);

  const handleAboutButtonClick = () => {
    setAboutButtonClicked(true);
    setMenuButtonClicked(false);
  };

  const handleMenuButtonClick = () => {
    setMenuButtonClicked(true);
    setAboutButtonClicked(false);
  };

  return (
    <>
      <Head>
        <title>Liberty House Specialties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div id="headertext">
  <h1 id="title">Liberty House Specialties</h1>
  <h2 id="location">11652 Liberty Street, Clinton LA</h2>
  <div className="topbuttons">
  <button  id="about" onClick={handleAboutButtonClick}>
    About Us
  </button>
  <button id="menu" onClick={handleMenuButtonClick}>
    Our Menu
  </button>
  <a href="tel:+1234567890" id="call">
    <button  id="call">
      Call in your order
    </button>
  </a>
  </div>
</div>
<div
        id="images"
        style={{
          opacity: aboutButtonClicked && !menuButtonClicked ? 0 : 1,
          transition: 'opacity 0.5s ease-in-out',
        }}
      >
        <Image
          id="coffeeimage"
          src="/images/coffee.jpg"
          alt=""
          width={367}
          height={350}
        ></Image>

        <Image id="teaimage"
        alt=""
        src="/images/tea.png"
        width={367}
        height={350}
        ></Image>

       <Image id="orangeimage"
        alt=""
        src="/images/orange.png"
        width={387}
        height={350}
        ></Image>
              </div>

      <div id="menucontents" style={{
          opacity: aboutButtonClicked && !menuButtonClicked ? 0 : 1,
          transition: 'opacity 0.5s ease-in-out',
        }}>
        <div id="menucoffee"><h1 id="menucoffeeheader">Liberty House Special Brew:</h1>
        <li className="coffeelist coffeelisttwelve">Hot<ul className="coffeelist subtwelvehot">(12oz.) ...2.95</ul><ul className="subtwelvecold">(16oz) ...3.95</ul></li><li className="coffeelistsix">Iced** <ul className="subsixhot">(12oz.) ...3.35</ul><ul className="subsixcold">(16oz.) ...4.25</ul></li>
        <h2 id="milknote">**Iced coffee can be served<br></br> with condensed milk. Yum!</h2>
       </div>

        <div className="menutea">
          <h1 className="tealist">Premium,<br></br> Organic Iced Tea</h1>
          <li id="teasix"><div id="teatype">Black/Hibiscus/Mixed </div><div id="teaprice">...2.29 </div></li>

        </div>
          <div id="menuorange"> <h1 id="orangeheader">Orange Juice</h1>
          <li id="orangeprice"><div id="wholeorange"><div id="glass">By the glass</div><div id="op">...2.29</div></div></li>
          </div>
     </div>
    </>
  );
}
